{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: {{ .Values.global.namespace }}
  labels:
    app: prometheus
    {{- include "foodios.labels" . | nindent 4 }}
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    rule_files:
      # - "first_rules.yml"
      # - "second_rules.yml"

    scrape_configs:
      # Prometheus itself
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      {{- if .Values.jaeger.enabled }}
      # Jaeger / OpenTelemetry Collector internal metrics
      - job_name: 'jaeger-internal'
        static_configs:
          - targets: ['jaeger:8888']
        scrape_interval: 5s
      {{- end }}

      {{- if .Values.otelCollector.enabled }}
      # OpenTelemetry Collector internal metrics
      - job_name: 'otel-collector-internal'
        static_configs:
          - targets: ['otel-collector:8888']
        scrape_interval: 5s

      - job_name: 'otel-collector-metrics'
        static_configs:
          - targets: ['otel-collector:8889']
        scrape_interval: 15s 
      {{- end }}

      - job_name: 'bgs-relay'
        static_configs:
          - targets: ['bgs:2471']
        scrape_interval: 5s

      - job_name: 'palomar'
        static_configs:
          - targets: ['palomar:3998']
        scrape_interval: 5s
      
         
{{- end }}
