{{- if .Values.pds.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pds-handles
  namespace: {{ .Values.global.namespace }}
  labels:
    app: pds
    {{- include "foodios.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.global.tls.enabled }}
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: "letsencrypt"
    {{- end }}
    {{- if .Values.global.developmentMode }}
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.global.tls.enabled }}
  tls:
  - hosts:
    - "*.{{ .Values.fqdns.pds }}"
    {{- if .Values.global.developmentMode }}
    secretName: {{ .Values.global.tls.secretName }}
    {{- end }}
  {{- end }}
  rules:
  - host: "*.{{ .Values.fqdns.pds }}"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pds
            port:
              number: {{ .Values.pds.port }}
{{- end }}
