{{- if and .Values.pds.enabled (not .Values.pds.debugMode) }}
apiVersion: v1
kind: Service
metadata:
  name: pds
  namespace: {{ .Values.global.namespace }}
  labels:
    app: pds
    {{- include "foodios.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.pds.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: pds
{{- end }}
