{{- if .Values.plc.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: plc
  namespace: {{ .Values.global.namespace }}
  labels:
    app: plc
    {{- include "foodios.labels" . | nindent 4 }}
spec:
  ports:
  - port: {{ .Values.plc.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: plc
{{- end }}
