{{- if .Values.relay.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: relay
  namespace: {{ .Values.global.namespace }}
  labels:
    app: relay
    {{- include "foodios.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.relay.apiPort }}
    targetPort: api
    protocol: TCP
    name: api
  - port: {{ .Values.relay.metricsPort }}
    targetPort: metrics
    protocol: TCP
    name: metrics
  selector:
    app: relay
{{- end }}
