global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Jaeger / OpenTelemetry Collector metrics
  # - job_name: 'jaeger'
  #   static_configs:
  #     - targets: ['jaeger:8889']
  #   scrape_interval: 5s

  # Jaeger / OpenTelemetry Collector internal metrics
  - job_name: 'jaeger-internal'
    static_configs:
      - targets: ['jaeger:8888']
    scrape_interval: 5s

  # OpenTelemetry Collector internal metrics
  - job_name: 'dd-collector-internal'
    static_configs:
      - targets: ['dd-collector:8888']
    scrape_interval: 5s

  - job_name: 'bgs-relay'
    static_configs:
      - targets: ['bgs:2471']
    scrape_interval: 5s

  - job_name: 'palomar'
    static_configs:
      - targets: ['palomar:3998']
    scrape_interval: 5s

  - job_name: 'caddy'
    static_configs:
      - targets: ['caddy:2020']
    scrape_interval: 5s


