global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # OpenTelemetry Collector metrics
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']
    scrape_interval: 5s

  # OpenTelemetry Collector internal metrics
  - job_name: 'otel-collector-internal'
    static_configs:
      - targets: ['otel-collector:8888']
    scrape_interval: 5s

  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:14269']
    scrape_interval: 5s

  - job_name: 'bgs-relay'
    static_configs:
      - targets: ['bgs:2471']
    scrape_interval: 5s

  - job_name: 'palomar'
    static_configs:
      - targets: ['palomar:3998']
    scrape_interval: 5s

  - job_name: 'caddy'
    static_configs:
      - targets: ['caddy:2020']
    scrape_interval: 5s


