{{- if .Values.socialEmbed.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: social-embed
  namespace: {{ .Values.global.namespace }}
  labels:
    app: social-embed
    {{- include "foodios.labels" . | nindent 4 }}
spec:
  ports:
  - port: {{ .Values.socialEmbed.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: social-embed
{{- end }}
